### ISSUE TITLE
New gemspec declares openstack itself as dependency

### ISSUE THREAD

**Issue by anbotero** [ruby-openstack/ruby-openstack#76]
With commit [582514930d2fde387d6cfc743d266895282327a1](https://github.com/ruby-openstack/ruby-openstack/commit/582514930d2fde387d6cfc743d266895282327a1), when regenerating gemspec file, you introduced openstack as its own dependency, causing circular dependency errors:

```
$ gem install --debug --backtrace --verbose openstack --version 2.0.0
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /home/myuser/.rbenv/versions/2.3.1/lib/ruby/2.3.0/resolv.rb:171 - LoadError
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=openstack
200 OK
Exception `Resolv::DNS::Config::NXDomain' at /home/myuser/.rbenv/versions/2.3.1/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvError' at /home/myuser/.rbenv/versions/2.3.1/lib/ruby/2.3.0/resolv.rb:494 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
Exception `Gem::Resolver::Molinillo::CircularDependencyError' at /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb:156 - There is a circular dependency between openstack and openstack
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between openstack and openstack
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb:156:in `add_edge'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb:103:in `block in add_child_vertex'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb:97:in `each'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/dependency_graph.rb:97:in `add_child_vertex'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:421:in `block in require_nested_dependencies_for'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:421:in `each'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:421:in `require_nested_dependencies_for'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:411:in `activate_spec'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:376:in `attempt_to_activate_new_spec'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:320:in `attempt_to_activate'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:147:in `process_topmost_state'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:72:in `resolve'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:191:in `resolve'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:368:in `resolve'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:484:in `resolve_dependencies'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:194:in `install_gem'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:255:in `block in install_gems'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `each'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `install_gems'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:158:in `execute'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in `invoke_with_build_args'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
  /home/myuser/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
  /home/myuser/.rbenv/versions/2.3.1/bin/gem:21:in `<main>'
```
Also, any particular reason OpenStack::VERSION stopped being used instead of hardcoding versions at gemspec?

Version `1.1.2` still installs just fine, although `1.2.0` doesn’t even exist in RubyGems listing.

Thanks!

**Comment by BirknerAlex** [comment]
Hello anbotero,

the Version 2.0.2 can be now installed at Rubygems.org without issues. This release fixed the gemspec file and should be working again. 

The reason why we are changed from OpenStack::VERSION to hardcoded is, we are using Jeweler for much easier distribution. 

I hope this release works for you.

Regards,
Alexander

**Comment by anbotero** [comment]
@BirknerAlex works perfectly, thank you!
